spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: hr
    password: hr
    
  jpa:
    show-sql: true
    
trainer:
  sub: Full-stack
  duration:  30